In [1]:
import numpy as np
import pandas as pd
import os
import random
import time
import math
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix
import gc

import torch
import torchvision
import torch.nn as nn
import torchinfo as info
import torchvision.transforms as transforms
import torchvision.transforms.functional as functional
from torchvision.transforms import v2

In [2]:
def set_seed(seed):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed(seed)
set_seed(500)

In [3]:
wd = os.getcwd()
device = torch.device('cuda')

## Model

In [4]:
from torchvision.models import swin_v2_t, Swin_V2_T_Weights

In [5]:
model = swin_v2_t(weights=Swin_V2_T_Weights.DEFAULT).to(device)
process = Swin_V2_T_Weights.DEFAULT.transforms()

In [6]:
for param in model.parameters():
    param.requires_grad = False
layers = []
layers.append(nn.Linear(in_features = 768, out_features = 256, bias = True))
layers.append(nn.ReLU())
layers.append(nn.Linear(in_features = 256, out_features = 9, bias = True))
model.head = nn.Sequential(*layers).to(device)

## Load and Process Data

In [7]:
class WeedsDataset():
    def __init__(self, labels, img_dir, transform = None):
        self.labels = pd.read_csv(labels)
        self.img_dir = img_dir
        self.transform = transform
        self.classes = self.labels[['Label','Species']].drop_duplicates().sort_values(by = 'Label').reset_index(drop = True)['Species']
        self.data = []
        self.train = []
        self.validation = []
        self.test = []
        
    # Load entire dataset into memory
    def __loaddata__(self):
        for row in self.labels.itertuples():
            filename = row.Filename
            label = torch.tensor(row.Label)
            img_path = os.path.join(self.img_dir, filename)
            image = torchvision.io.read_image(img_path)
            self.data.append([image,label])
        del self.labels
        print('Data has been loaded')

    # Split into train/validation/test
    def __split__(self):
        random.shuffle(self.data)
        n = len(self.data)
        n_train = round(n * 0.8)
        n_valid = round(n * 0.1)
        
        self.train = self.data[:n_train]
        self.valid = self.data[n_train:n_train + n_valid]
        self.test = self.data[n_train + n_valid:]
        del self.data
        gc.collect()
        
        print('Data has been split')
        print('Size of training set is {}'.format(len(self.train)))
        print('Size of validation set is {}'.format(len(self.valid)))
        print('Size of test set is {}'.format(len(self.test)))

    # Augment training data
    def __augment__(self, frac):
        aug = []
        color_jitter = transforms.ColorJitter(brightness = 0.3, contrast = 0.2, saturation = 0.3, hue = 0.0)
        n = round(len(self.train) * frac / 3)
        
        rotate_90 = random.sample(self.train, n)
        for row in rotate_90:
            image = row[0].clone()
            image = transforms.functional.rotate(image, 90)
            image = color_jitter(image)
            row[0] = image
        
        rotate_180 = random.sample(self.train, n)
        for row in rotate_180:
            image = row[0].clone()
            image = transforms.functional.rotate(image, 180)
            image = color_jitter(image)
            row[0] = image
        
        rotate_270 = random.sample(self.train, n)
        for row in rotate_270:
            image = row[0].clone()
            image = transforms.functional.rotate(image, 270)
            image = color_jitter(image)
            row[0] = image
     
        self.train += rotate_90 + rotate_180 + rotate_270  
        print('Data has been augmented')
        print('Size of training set is {}'.format(len(self.train)))

    # Apply model transformation
    def __apply__(self):
        for i in range(len(self.train)):
            self.train[i][0] = self.transform(self.train[i][0])
        for i in range(len(self.valid)):
            self.valid[i][0] = self.transform(self.valid[i][0])
        for i in range(len(self.test)):
            self.test[i][0] = self.transform(self.test[i][0]) 
        print('Data has been transformed')

In [8]:
# Run functions to load and process data
weeds = WeedsDataset(rf'{wd}\labels.csv', rf'{wd}\images', process)
weeds.__loaddata__()
weeds.__split__()
weeds.__augment__(0.6)
weeds.__apply__()

Data has been loaded
Data has been split
Size of training set is 14007
Size of validation set is 1751
Size of test set is 1751
Data has been augmented
Size of training set is 22410
Data has been transformed


## Functions

In [9]:
def get_batch(dataset, current_index, batch_size):
    images,labels = zip(*dataset[current_index:current_index+batch_size])
    return torch.stack(images, dim = 0).to(device), torch.stack(labels).to(device)
    
def train_one_epoch(model, dataset, batch_size):
    batches = math.floor(len(dataset.train)/batch_size)
    current_index = 0
    running_loss = 0
    random.shuffle(dataset.train)

    for i in range(batches):
        inputs,labels = get_batch(dataset.train, current_index, batch_size)
        current_index += batch_size
        optimizer.zero_grad(set_to_none=True)
        outputs = model(inputs)
        loss = loss_fn(outputs, labels)
        loss.backward()
        optimizer.step()
        running_loss += loss.cpu().item()

    remainder = len(weeds.train)%batch_size
    if remainder != 0:
        inputs,labels = get_batch(dataset.train, current_index, batch_size)
        optimizer.zero_grad()
        outputs = model(inputs)
        loss = loss_fn(outputs, labels)
        loss.backward()
        optimizer.step()
        running_loss += loss.cpu().item()
        batches += 1
    
    return running_loss/batches

def validate(model, dataset, batch_size):
    batches = math.floor(len(weeds.valid)/batch_size)
    current_index = 0
    running_loss = 0
    
    for i in range(batches):
        inputs,labels = get_batch(dataset.valid, current_index, batch_size)
        current_index += batch_size
        output = model(inputs)
        running_loss += loss_fn(output, labels).cpu().item()

    remainder = len(weeds.valid)%batch_size
    if remainder != 0:
        inputs,labels = get_batch(dataset.valid, current_index, batch_size)
        output = model(inputs)
        running_loss += loss_fn(output, labels).cpu().item()
        batches += 1
    
    return running_loss/batches

In [10]:
def train(epochs, model, dataset, batch_size, folder_name):
    best_vloss = 1000
    current_vloss = 0
    epoch_counter = 1
    start = time.perf_counter()
    
    if not os.path.exists('{}\{}'.format(wd,folder_name)):
        os.makedirs('{}\{}'.format(wd,folder_name))
        
    for epoch in range(epochs):
        print('EPOCH {}:'.format(epoch_counter))
        model.train()
        avg_loss = train_one_epoch(model, dataset, batch_size)
        
        model.eval()
        with torch.no_grad():
            current_vloss = validate(model, dataset, batch_size)

        print('LOSS train {} valid {}'.format(avg_loss, current_vloss))
        if current_vloss <= best_vloss:
                best_vloss = current_vloss
                print('New best validation loss')
        print('Lr is currently {}'.format(scheduler.get_last_lr()))
        scheduler.step(current_vloss)

        if epoch_counter > epochs/4:
            model_path = '{}\model_{}'.format(folder_name, epoch_counter)
            torch.save(model.state_dict(), model_path)
            
        epoch_counter += 1

    print('Average time taken per epoch is {}s'.format((end - start)/epochs))
    return

## Training with only classifier unfrozen

In [11]:
loss_fn = nn.CrossEntropyLoss().to(device)
optimizer = torch.optim.SGD(model.parameters(), lr = 0.012, momentum = 0.8)
scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(optimizer, factor = 0.5)

In [12]:
train(120,model,weeds,50,'swin_t')

EPOCH 1:
LOSS train 1.08932538446711 valid 0.6715267557236884
New best validation loss
Lr is currently [0.012]
EPOCH 2:
LOSS train 0.7961166400155405 valid 0.5107650498135222
New best validation loss
Lr is currently [0.012]
EPOCH 3:
LOSS train 0.7126963263365101 valid 0.4574437278012435
New best validation loss
Lr is currently [0.012]
EPOCH 4:
LOSS train 0.6614561003937753 valid 0.4255613883336385
New best validation loss
Lr is currently [0.012]
EPOCH 5:
LOSS train 0.6214973850213075 valid 0.401267326850858
New best validation loss
Lr is currently [0.012]
EPOCH 6:
LOSS train 0.5964046476412987 valid 0.3663164745602343
New best validation loss
Lr is currently [0.012]
EPOCH 7:
LOSS train 0.5758911241136309 valid 0.35705515473253197
New best validation loss
Lr is currently [0.012]
EPOCH 8:
LOSS train 0.5440605483899403 valid 0.32772717216155595
New best validation loss
Lr is currently [0.012]
EPOCH 9:
LOSS train 0.5270892139067894 valid 0.32824807345039314
Lr is currently [0.012]
EPOCH 10

KeyboardInterrupt: 

## Evaluation

In [13]:
# Formula for F1: (2 * FP) / (2 * TP + FP + FN) OR 2 * (Precision * Recall) / (Precision + Recall)
# Formula for Precision: TP / (TP + FP)
# Formula for Recall: TP / (TP + FN)
def metrics(TP,FP,FN):
    if TP > 0:
        precision = TP / (TP + FP)
        recall = TP / (TP + FN)
        F1  = TP / (TP + 0.5 * (FP + FN))
    else:
        precision = 0
        recall = 0
        F1  = 0
    return precision, recall, F1
    
def evaluate(model, dataset, batch_size):
    start = time.perf_counter()
    total = 0
    correct = 0
    batches = math.floor(len(dataset.test) / batch_size)
    current_index = 0
    model.eval()
    
    all_preds = []
    all_labels = []

    for i in range(batches):
        inputs, labels = get_batch(dataset.test, current_index, batch_size)
        current_index += batch_size
        prediction = torch.argmax(model(inputs), dim=1)
        
        correct += sum(prediction == labels).item()
        total += batch_size

        all_preds.extend(prediction.cpu().numpy())
        all_labels.extend(labels.cpu().numpy())

    remainder = len(dataset.test) % batch_size
    if remainder != 0:
        inputs, labels = get_batch(dataset.test, current_index, remainder)
        prediction = torch.argmax(model(inputs), dim=1)
        
        correct += sum(prediction == labels).item()
        total += remainder

        all_preds.extend(prediction.cpu().numpy())
        all_labels.extend(labels.cpu().numpy())

    accuracy = 100 * correct / total

    # Compute Metrics for individual classes
    num_classes = len(dataset.classes) 
    conf_matrix = confusion_matrix(all_labels, all_preds, labels=np.arange(num_classes))
    print(conf_matrix)

    for i in range(num_classes):
        TP = conf_matrix[i, i]  # True Positives
        FP = np.sum(conf_matrix[:, i]) - TP  # False Positives
        FN = np.sum(conf_matrix[i, :]) - TP  # False Negatives
        precision,recall,F1 = metrics(TP, FP, FN)
        print(f"Precision for class {dataset.classes[i]}: {precision:.4f}")
        print(f"Recall for class {dataset.classes[i]}: {recall:.4f}")
        print(f"F1-score for class {dataset.classes[i]}: {F1:.4f}")
    print('Total Accuracy is {}%'.format(accuracy))
    
    end = time.perf_counter()
    print('Time taken is {}'.format(end - start))

In [15]:
model_path = os.path.join(wd,'swin_t','model_68')
model.load_state_dict(torch.load(model_path, weights_only = True))

<All keys matched successfully>

In [16]:
with torch.no_grad():
    evaluate(model, weeds, 50)

[[ 85   1   0   0   0   0   2  12   6]
 [  2  88   1   0   1   0   0   2   6]
 [  0   0  95   1   2   0   0   0   0]
 [  2   0   0  85   3   0   1   0   6]
 [  0   0   1   0 113   0   0   0   2]
 [  0   0   1   0   1  94   0   0   6]
 [  0   0   0   0   0   0  87   0   7]
 [  6   0   0   1   0   1   0  81   3]
 [  4   4   3   6   9   6   6   5 903]]
Precision for class Chinee apple: 0.8586
Recall for class Chinee apple: 0.8019
F1-score for class Chinee apple: 0.8293
Precision for class Lantana: 0.9462
Recall for class Lantana: 0.8800
F1-score for class Lantana: 0.9119
Precision for class Parkinsonia: 0.9406
Recall for class Parkinsonia: 0.9694
F1-score for class Parkinsonia: 0.9548
Precision for class Parthenium: 0.9140
Recall for class Parthenium: 0.8763
F1-score for class Parthenium: 0.8947
Precision for class Prickly acacia: 0.8760
Recall for class Prickly acacia: 0.9741
F1-score for class Prickly acacia: 0.9224
Precision for class Rubber vine: 0.9307
Recall for class Rubber vine: 0